export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_END = 'AJAX_END';
export const AJAX_ERROR = 'AJAX_ERROR';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';

// Authentication
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REDIRECTED = 'REDIRECTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// User
export const FETCH_LOGGEDIN_USERDATA_BEGIN = 'FETCH_LOGGEDIN_USERDATA_BEGIN';
export const FETCH_LOGGEDIN_USERDATA_SUCCESS = 'FETCH_LOGGEDIN_USERDATA_SUCCESS';
export const FETCH_LOGGEDIN_USERDATA_ERROR = 'FETCH_LOGGEDIN_USERDATA_ERROR';
export const UPDATE_LOGGEDIN_USERDATA = 'UPDATE_LOGGEDIN_USERDATA';

export const FETCH_TIMELINE_USERDATA_BEGIN = 'FETCH_TIMELINE_USERDATA_BEGIN';
export const FETCH_TIMELINE_USERDATA_SUCCESS = 'FETCH_TIMELINE_USERDATA_SUCCESS';
export const FETCH_TIMELINE_USERDATA_ERROR = 'FETCH_TIMELINE_USERDATA_ERROR';
export const UPDATE_TIMELINE_USERDATA = 'UPDATE_TIMELINE_USERDATA';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const FETCH_ALLUSERS_SUCCESS = 'FETCH_ALLUSERS_SUCCESS';
export const FETCH_ALLUSERS_BEGIN = 'FETCH_ALLUSERS_BEGIN';
export const FETCH_ALLUSERS_ERROR = 'FETCH_ALLUSERS_ERROR';

export const PROMOTE_USER_SUCCESS = 'PROMOTE_USER_SUCCESS';
export const PROMOTE_USER_BEGIN = 'PROMOTE_USER_BEGIN';
export const PROMOTE_USER_ERROR = 'PROMOTE_USER_ERROR';

export const DEMOTE_USER_SUCCESS = 'PROMOTE_USER_SUCCESS';
export const DEMOTE_USER_BEGIN = 'PROMOTE_USER_BEGIN';
export const DEMOTE_USER_ERROR = 'PROMOTE_USER_ERROR';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CHANGE_TIMELINE_USERDATA_SUCCESS = 'CHANGE_TIMELINE_USERDATA_SUCCESS';
export const CHANGE_TIMELINE_USERDATA_BEGIN = 'CHANGE_TIMELINE_USERDATA_BEGIN';
export const CHANGE_TIMELINE_USERDATA_ERROR = 'CHANGE_TIMELINE_USERDATA_ERROR';

export const CHANGE_USERROLE = 'CHANGE_USERROLE';

// Picture
export const ADD_PICTURE_SUCCESS = 'ADD_PICTURE_SUCCESS';
export const ADD_PICTURE_BEGIN = 'ADD_PICTURE_BEGIN';
export const ADD_PICTURE_ERROR = 'ADD_PICTURE_ERROR';

export const REMOVE_PICTURE_SUCCESS = 'REMOVE_PICTURE_SUCCESS';
export const REMOVE_PICTURE_BEGIN = 'REMOVE_PICTURE_BEGIN';
export const REMOVE_PICTURE_ERROR = 'REMOVE_PICTURE_ERROR';

export const FETCH_PICTURE_BEGIN = 'FETCH_PICTURE_BEGIN';
export const FETCH_PICTURE_SUCCESS = 'FETCH_PICTURE_SUCCESS';
export const FETCH_PICTURE_ERROR = 'FETCH_PICTURE_ERROR';

export const CHANGE_PICTURES_SUCCESS = 'CHANGE_PICTURES_SUCCESS';
export const CHANGE_PICTURES_BEGIN = 'CHANGE_PICTURES_BEGIN';
export const CHANGE_PICTURES_ERROR = 'CHANGE_PICTURES_ERROR';

export const UPDATE_PICTURES = 'UPDATE_PICTURES';

export const FINDBYUSERNAME_LOGS_SUCCESS = 'FINDBYUSERNAME_LOGS_SUCCESS';
export const FINDBYUSERNAME_LOGS_BEGIN = 'FINDBYUSERNAME_LOGS_BEGIN';
export const FINDBYUSERNAME_LOGS_ERROR = 'FINDBYUSERNAME_LOGS_ERROR';

export const CLEARBYUSERNAME_LOGS_SUCCESS = 'CLEARBYUSERNAME_LOGS_SUCCESS';
export const CLEARBYUSERNAME_LOGS_BEGIN = 'CLEARBYUSERNAME_LOGS_BEGIN';
export const CLEARBYUSERNAME_LOGS_ERROR = 'CLEARBYUSERNAME_LOGS_ERROR';

export const FETCH_ALL_LOGS_SUCCESS = 'FETCH_ALL_LOGS_SUCCESS';
export const FETCH_ALL_LOGS_BEGIN = 'FETCH_ALL_LOGS_BEGIN';
export const FETCH_ALL_LOGS_ERROR = 'FETCH_ALL_LOGS_ERROR';

export const CLEAR_ALL_LOGS_SUCCESS = 'CLEAR_ALL_LOGS_SUCCESS';
export const CLEAR_ALL_LOGS_BEGIN = 'CLEAR_ALL_LOGS_BEGIN';
export const CLEAR_ALL_LOGS_ERROR = 'CLEAR_ALL_LOGS_ERROR';

export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_BEGIN = 'SEARCH_RESULTS_BEGIN';
export const SEARCH_RESULTS_ERROR = 'SEARCH_RESULTS_ERROR';
